### ISSUE TITLE
Issues in SWAN page

### ISSUE THREAD

**Issue by AnneThKu** [subnero1/subnero1.github.io#205]
Below issues to be fixed in the new SWAN page:
- [ ] Banner text goes under the navbar sometimes.
- [ ] "Components of SWAN" section resizes based on content length.
- [ ] It would be good ti change the image also on hover of "Dense datasets in real-time, Safe and Sustainable.." section.

**Comment by esthertanhj** [comment]
1) The sentence "The Subnero Water Assessment Network (**SWAN**) is a network that provides real-time monitoring and analysis of water quality at various depths along with the ability to collect water samples and can span across diverse assets, including SwanBots, sensor nodes, and data analytics systems." is too long.

I propose to update it to "The Subnero Water Assessment Network (**SWAN**) is a network that provides real-time monitoring and analysis of water quality at various depths, along with the ability to collect water samples. The SWAN can span across diverse assets, including SwanBots, sensor nodes, and data analytics systems."

2) For the section on "Monitoring dissolved oxygen", please add an "s" for the word "generate"

i.e. SWAN generate**s** alerts based on user settings, which notifies the user when dissolved oxygen levels go beyond a threshold value, for corrective measures to be taken in time.

Dissolved oxygen in subsequent usages can be replaced with "DO" if the acronym is included at the front.

3) Under SwanCloud, there should be a hyphen for "web based" >> should be "web-based".

4) Can we rename the "SWAN brochure V2" file to "SWAN brochure"?

5) Instead of the 2020 news, we can perhaps use a more recent link "https://www.yumpu.com/en/document/read/66222230/water-wastewater-asia-january-february-2022/31" with the header "SWAN's feature in Water & Wastewater Asia (WWA) magazine" - Feb 2022?
