### ISSUE TITLE
Quicklinks page fixes

### ISSUE THREAD

**Issue by manuignatius** [subnero1/subnero1.github.io#210]
Too small a margin
<img width="122" alt="Screenshot 2022-05-02 at 7 04 47 AM" src="https://user-images.githubusercontent.com/4144181/166231743-edb09b45-5bd1-4be0-b45e-cb8f98b6748e.png">

Alignment issues for the text
<img width="193" alt="Screenshot 2022-05-02 at 7 04 52 AM" src="https://user-images.githubusercontent.com/4144181/166231757-600dfa39-5921-4dcf-8147-4d539df77983.png">

**Comment by christopherkzj** [comment]
2. Alignment issues for the text

fixed in pr https://github.com/subnero1/subnero1.github.io/pull/224

![screencapture-127-0-0-1-4000-quicklinks-2022-08-29-15_42_19](https://user-images.githubusercontent.com/112359926/187150076-e0ee90fb-709c-4ece-9a7b-634ad4f5b064.png)
![screencapture-127-0-0-1-4000-quicklinks-2022-08-29-15_41_58](https://user-images.githubusercontent.com/112359926/187150102-8f185993-3ff7-4962-b874-923c39147238.png)

**Comment by christopherkzj** [comment]
1. Too small a margin 

Current product site looks fine on mobile, dont have small margin issue

![WhatsApp Image 2022-08-29 at 3 52 12 PM](https://user-images.githubusercontent.com/112359926/187152222-92785b47-8bb6-43b0-bad2-514d6c87552c.jpeg)
