### ISSUE TITLE
Bigger logo

### ISSUE THREAD

**Issue by sayanee** [subnero1/subnero1.github.io#43]
## Current situation

![image](https://user-images.githubusercontent.com/413879/46061800-6b0df000-c19a-11e8-99a6-0ea196b63460.png)

## Suggested situation

Might need to make the height of the main menu on the homepage slightly bigger.

![image](https://user-images.githubusercontent.com/413879/46061769-52053f00-c19a-11e8-9dfd-8a14d403a300.png)

**Comment by notthetup** [comment]
This might have to scale with screen size. A larger logo would look huge on a small screen.

**Comment by AnneThKu** [comment]
Logo size increased in the landing page  and text size of the menu increased in the landing page and other pages for bigger screens.

**Comment by notthetup** [comment]
Looking at the logo on various screen sizes. Definitely bigger 👍🏽.

But the location keeps moving. I'm suspecting some padding is defined in pixels instead of %.

![Screenshot 2019-04-16 12 40 56](https://user-images.githubusercontent.com/553140/56182543-43eb1300-6045-11e9-9000-fc7e4a5f3750.png)
<img width="1281" alt="Screenshot 2019-04-16 12 41 10" src="https://user-images.githubusercontent.com/553140/56182544-4483a980-6045-11e9-9d90-7b877435382d.png">
<img width="695" alt="Screenshot 2019-04-16 12 41 59" src="https://user-images.githubusercontent.com/553140/56182546-4483a980-6045-11e9-9ff7-2ab0a0f40a5a.png">

**Comment by AnneThKu** [comment]
I think currently it is changing due to the min-width (75vw) set for the top-bar. I changed it to 90vw, the position seems to be almost same.

![Big_Logo_ScreenSize_3](https://user-images.githubusercontent.com/42397354/56199367-5f6b1380-606f-11e9-9ebd-f83fc8a6e871.png)

![Big_Logo_ScreenSize_2](https://user-images.githubusercontent.com/42397354/56199376-65f98b00-606f-11e9-93aa-8c9b0d352c89.png)

![Big_Logo_ScreenSize_1](https://user-images.githubusercontent.com/42397354/56199382-67c34e80-606f-11e9-80e5-a44056b5a46f.png)
