### ISSUE TITLE
Add script to load random landing page images on page load/refresh

### ISSUE THREAD

**Issue by manuignatius** [subnero1/subnero1.github.io#7]
Currently the landing page image changes during every git commit.

**Comment by notthetup** [comment]
I would prefer to do this using something server side. Doing it on the client side is going to be really ugly (white flash as the image is reloaded).

Since we're using jekyll, I don't think we have much access to do this on server side, but we can investigate something like https://www.cloudflare.com/products/cloudflare-workers/

**Comment by AnneThKu** [comment]
modified index.html to load random images.
